name: go
version: v4.0.0-rc.3
schema: 1
scm: github.com/pubnub/go
changelog:
  - version: v4.0.0-rc.3
    changes:
      - type: bug
        text: Reconnection fixes
  - version: v4.0.0-rc.2
    changes:
      - type: bug
        text: auth fix
      - type: bug
        text: Signature does not match fix when both secret key and auth is set
      - type: improvement
        text: cleanup
      - type: improvement
        text: integration tests fixes for the changes done on auth
  - version: v4.0.0-rc.1
    changes:
      - type: bug
        text: set state refactor fix
  - version: v4.0.0-beta.8
    changes:
      - type: improvement
        text: Subscribe with state
  - version: v4.0.0-beta.7
    changes:
      - type: improvement
        text: cipher improvements
  - version: v4.0.0-beta.6
    changes:
      - type: improvement
        text: Fire, Fetch, HereNowRequest
  - version: v4.0.0-beta.5
    changes:
      - type: improvement
        text: add subscribe builder
  - version: v4.0.0-beta.4
    changes:
      - type: improvement
        text: add Telemetry Manager
  - version: v4.0.0-beta.3
    changes:
      - type: improvement
        text: add Destroy() method
  - version: v4.0.0-beta.2
    changes:
      - type: impovement
        text: add reconnection manager
      - type: impovement
        text: rename list, remove, add, delete channel of channel groups
      - type: bug
        text: fix comma encoding
      - type: bug
        text: fix signature
  - version: v4.0.0-beta
    changes:
      - type: impovement
        text: initial beta
features:
  access:
    - ACCESS-GRANT
    - ACCESS-SECRET-KEY-ALL-ACCESS
  channel-groups:
    - CHANNEL-GROUPS-ADD-CHANNELS
    - CHANNEL-GROUPS-REMOVE-CHANNELS
    - CHANNEL-GROUPS-REMOVE-GROUPS
    - CHANNEL-GROUPS-LIST-CHANNELS-IN-GROUP
  notify:
    - REQUEST-MESSAGE-COUNT-EXCEEDED
  push:
    - PUSH-ADD-DEVICE-TO-CHANNELS
    - PUSH-REMOVE-DEVICE-FROM-CHANNELS
    - PUSH-LIST-CHANNELS-FROM-DEVICE
    - PUSH-REMOVE-DEVICE
  presence:
    - PRESENCE-HERE-NOW
    - PRESENCE-WHERE-NOW
    - PRESENCE-GET-STATE
    - PRESENCE-SET-STATE
    - PRESENCE-HEARTBEAT
  publish:
    - PUBLISH-STORE-FLAG
    - PUBLISH-RAW-JSON
    - PUBLISH-WITH-METADATA
    - PUBLISH-GET
    - PUBLISH-POST
  storage:
    - STORAGE-REVERSE
    - STORAGE-INCLUDE-TIMETOKEN
    - STORAGE-START-END
    - STORAGE-COUNT
  time:
    - TIME-TIME
  subscribe:
    - SUBSCRIBE-CHANNELS
    - SUBSCRIBE-CHANNEL-GROUPS
    - SUBSCRIBE-PRESENCE-CHANNELS
    - SUBSCRIBE-PRESENCE-CHANNEL-GROUPS
    - SUBSCRIBE-WITH-TIMETOKEN
    - SUBSCRIBE-WILDCARD
    - SUBSCRIBE-FILTER-EXPRESSION
    - SUBSCRIBE-PUBLISHER-UUID
supported-platforms:
  -
    version: PubNub Go SDK
    platforms:
      - FreeBSD 8-STABLE or later, amd64, 386
      - Linux 2.6 or later, amd64, 386.
      - Mac OS X 10.8 or later, amd64
      - Windows 7 or later, amd64, 386
