language: go

go:
  - 1.7.6
  - 1.8.7
  - 1.9.7
  - 1.10.3
  - 1.11.1
  - tip
  
matrix:
  allow_failures:
    - go: tip
  fast_finish: true
go_import_path: github.com/pubnub/go  

install:
  - mkdir -p $GOPATH/src/github.com/pubnub
  - go get golang.org/x/net/context
  - go get github.com/wadey/gocovmerge
  - go get github.com/stretchr/testify
  - go get github.com/satori/go.uuid
  - go get golang.org/x/text/secure/bidirule
  - go get golang.org/x/text/unicode/bidi
  - go get golang.org/x/text/unicode/norm

script:
  - bash ./scripts/run-tests.sh

after_success:
    - bash <(curl -s https://codecov.io/bash)
