language: go

go:
  - 1.7.1
  - 1.7.3
  - 1.7.4
  - 1.8
  - 1.9
  - tip
  
matrix:
  allow_failures:
    - go: tip
  fast_finish: true
go_import_path: github.com/pubnub/go  

install:
  - mkdir -p $GOPATH/src/github.com/pubnub

script:
  make -f Makefile

after_success:
    - bash <(curl -s https://codecov.io/bash)
addons:
  srcclr: true
