language: go

go:
  - 1.7.1
  - 1.7.3
  - 1.7.4
  - 1.8
  - 1.9
  - 1.9.7
  - 1.10.3
  - tip
  
matrix:
  allow_failures:
    - go: tip
  fast_finish: true
go_import_path: github.com/pubnub/go  

install:
  - mkdir -p $GOPATH/src/github.com/pubnub
  - go get golang.org/x/net/context
  - go get github.com/wadey/gocovmerge
  - go get github.com/stretchr/testify
  - go get github.com/satori/go.uuid

script:
  - bash ./scripts/run-tests.sh

after_success:
    - bash <(curl -s https://codecov.io/bash)
addons:
  srcclr: true
